# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('begin_charge', models.DateTimeField()),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '`vinnetgw`.`fee_charge`',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GlobalAccount',
            fields=[
                ('objectid', models.BigAutoField(primary_key=True, serialize=False)),
                ('accountname', models.CharField(max_length=50)),
                ('phoneversion', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('lastlogintime', models.DateTimeField(blank=True, null=True)),
                ('resettimes', models.SmallIntegerField(blank=True, null=True)),
                ('createtime', models.DateTimeField(blank=True, null=True)),
                ('modifytime', models.DateTimeField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('api_key', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'global_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GlobalWatch',
            fields=[
                ('ptuid', models.IntegerField(primary_key=True, serialize=False)),
                ('io_options', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('sn', models.IntegerField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=20, null=True)),
                ('firstactivetime', models.DateTimeField(blank=True, null=True)),
                ('producetime', models.DateTimeField(blank=True, null=True)),
                ('akey', models.IntegerField(blank=True, null=True)),
                ('imei', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('iccid', models.CharField(blank=True, max_length=20, null=True)),
                ('imsi', models.CharField(blank=True, max_length=15, null=True)),
                ('term_id', models.CharField(blank=True, max_length=50, null=True)),
                ('qr', models.CharField(blank=True, max_length=50, null=True)),
                ('alias', models.CharField(blank=True, max_length=20, null=True)),
                ('tel', models.CharField(blank=True, max_length=13, null=True)),
                ('smac', models.CharField(blank=True, max_length=6, null=True)),
                ('mcc', models.SmallIntegerField(blank=True, null=True)),
                ('mnc', models.IntegerField(blank=True, null=True)),
                ('cdma_tid', models.CharField(blank=True, max_length=20, null=True)),
                ('uimid', models.CharField(blank=True, max_length=8, null=True)),
                ('esn', models.IntegerField(blank=True, null=True)),
                ('meid', models.CharField(blank=True, max_length=14, null=True)),
                ('linkstate', models.IntegerField(blank=True, null=True)),
                ('soundstate', models.IntegerField(blank=True, null=True)),
                ('messagestate', models.IntegerField(blank=True, null=True)),
                ('positionstate', models.IntegerField(blank=True, null=True)),
                ('sosstate', models.IntegerField(blank=True, null=True)),
                ('dotstate', models.IntegerField(blank=True, null=True)),
                ('lastuptime', models.DateTimeField(blank=True, null=True)),
                ('province', models.CharField(blank=True, max_length=16, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('lastposition', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('modifytime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'global_watch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SmsSendLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_number', models.CharField(max_length=20)),
                ('gen_date', models.DateTimeField()),
                ('content', models.CharField(max_length=350)),
                ('code', models.IntegerField()),
                ('message', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '`vinnetgw`.`sms_send_log`',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Topup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('from_account', models.CharField(max_length=20)),
                ('card_value', models.IntegerField()),
                ('gen_date', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '`vinnetgw`.`topup_trans`',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnbindHistory',
            fields=[
                ('objectid', models.BigAutoField(primary_key=True, serialize=False)),
                ('ptuid', models.IntegerField()),
                ('accountname', models.CharField(max_length=50)),
                ('createtime', models.DateTimeField()),
            ],
            options={
                'db_table': 'unbind_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WatchAccountRelation',
            fields=[
                ('objectid', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('flag', models.IntegerField(blank=True, null=True)),
                ('createtime', models.DateTimeField(blank=True, null=True)),
                ('babyname', models.CharField(blank=True, max_length=50, null=True)),
                ('babybirthday', models.DateField(blank=True, null=True)),
                ('babysex', models.IntegerField(blank=True, null=True)),
                ('babygrade', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'watch_account_relation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WatchProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('po', models.CharField(max_length=10)),
            ],
            options={
                'db_table': '`cms_product_db`.`watch_product`',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('html', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Post')),
            ],
        ),
    ]
